Repository Homeat/HOMEAT_iOS, pull requests merged in 2024-05, with the labels that each got.

#52 Feat/#48 카카오로그인 구현 및 키체인 라이브러리 추가
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HOMEAT/Application/AppDelegate.swift
  HOMEAT/Application/SceneDelegate.swift
  HOMEAT/Global/Resource/Assets.xcassets/kakaoLogo.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/kakaoLogo.imageset/kakaoLogo.png
  HOMEAT/Global/Resource/Assets.xcassets/kakaoLogo.imageset/kakaoLogo2.png
  HOMEAT/Global/Resource/Assets.xcassets/kakaoLogo.imageset/kakaoLogo3.png
  HOMEAT/Info.plist
  HOMEAT/Network/Base/APIRequestLoader.swift
  HOMEAT/Network/Base/BaseResponse.swift
  HOMEAT/Network/Base/HOMEATRequestInterceptor.swift
  HOMEAT/Network/Base/HTTPHeaderField.swift
  HOMEAT/Network/Base/KeychainHandler.swift
  HOMEAT/Network/Base/NetworkResult.swift
  HOMEAT/Network/Base/NetworkService.swift
  HOMEAT/Network/Base/TargetType.swift
  HOMEAT/Network/Onboarding/DTO/Request/KakaoLoginRequestBodyDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/KakaoLoginResponseDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/TokenRefreshResponseDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/UserInfoResponseDTO.swift
  HOMEAT/Network/Onboarding/Router/OnboardingTarget.swift
  HOMEAT/Network/Onboarding/Service/OnboardingService.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
Labels: :computer: API, 석호

#54 Feature/homeat 28
  HOMEAT/Presentation/HomeScene/Components/TagButton.swift
  HOMEAT/Presentation/HomeScene/Controller/PayAddViewController.swift
  HOMEAT/Presentation/HomeScene/View/PayCheckView.swift
Labels: :sparkles: Feature, 상준

#56 [HOMEAT-31] Feat [#55] 사라진 파일 찾기
  HOMEAT.xcodeproj/project.pbxproj
Labels: :lady_beetle: BugFix, 석호

#63 [HOMEAT-36] Feat [#60] 이메일 로그인 통신 구현
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Base/APIRequestLoader.swift
  HOMEAT/Network/Base/BaseResponse.swift
  HOMEAT/Network/Base/HOMEATRequestInterceptor.swift
  HOMEAT/Network/Base/HTTPHeaderField.swift
  HOMEAT/Network/Base/TargetType.swift
  HOMEAT/Network/Onboarding/DTO/Request/EmailLoginRequestBodyDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/EmailLoginResponseDTO.swift
  HOMEAT/Network/Onboarding/Router/OnboardingTarget.swift
  HOMEAT/Network/Onboarding/Service/OnboardingService.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/OnBoardingViewController.swift
Labels: :computer: API

#64 Feat/#59 홈잇 소비분석 서버 연동
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Analysis/DTO/Request/AnalysisMonthRequestBodyDTO.swift
  HOMEAT/Network/Analysis/DTO/Request/AnalysisWeekRequestBodyDTO.swift
  HOMEAT/Network/Analysis/DTO/Response/AnalysisMonthResponseDTO.swift
  HOMEAT/Network/Analysis/DTO/Response/AnalysisWeekResponseDTO.swift
  HOMEAT/Network/Analysis/Router/AnalysisTarget.swift
  HOMEAT/Network/Analysis/Service/AnalysisService.swift
  HOMEAT/Network/Base/NetworkService.swift
  HOMEAT/Network/WeekLook/DTO/Request/WeekLookRequestBodyDTO.swift
  HOMEAT/Network/WeekLook/DTO/Response/WeekLookResponseDTO.swift
  HOMEAT/Network/WeekLook/Router/WeekLookTarget.swift
  HOMEAT/Network/WeekLook/Service/WeekLookService.swift
  HOMEAT/Presentation/ReportScene/Controller/AnalysisViewController.swift
  HOMEAT/Presentation/ReportScene/View/MonthView.swift
  HOMEAT/Presentation/ReportScene/View/WeakView.swift
Labels: :computer: API, 민솔

#67 [HOMEAT-41] Feat[#65] 월뷰,주간뷰 action 리팩토링
  HOMEAT/Presentation/ReportScene/View/MonthView.swift
  HOMEAT/Presentation/ReportScene/View/WeakView.swift
Labels: :hammer: Refactor, 민솔

#69 [HOMEAT-30] Feat[#53] 집밥토크 포스트뷰, 댓글창 구현
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/icon-4.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/icon-4.imageset/icon-4.png
  HOMEAT/Global/Resource/Assets.xcassets/icon-4.imageset/icon-4@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/icon-4.imageset/icon-4@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/icon-5.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/icon-5.imageset/icon-5.png
  HOMEAT/Global/Resource/Assets.xcassets/icon-5.imageset/icon-5@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/icon-5.imageset/icon-5@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/isHeartSelected.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/isHeartSelected.imageset/full heart.png
  HOMEAT/Global/Resource/Assets.xcassets/isHeartSelected.imageset/full heart@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/isHeartSelected.imageset/full heart@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/isHeartUnselected.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/isHeartUnselected.imageset/Icon.png
  HOMEAT/Global/Resource/Assets.xcassets/isHeartUnselected.imageset/Icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/isHeartUnselected.imageset/Icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/isReply.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/isReply.imageset/icon-3.png
  HOMEAT/Global/Resource/Assets.xcassets/isReply.imageset/icon-3@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/isReply.imageset/icon-3@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/isSmallHeartSelected.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/isSmallHeartSelected.imageset/icon-2.png
  HOMEAT/Global/Resource/Assets.xcassets/isSmallHeartSelected.imageset/icon-2@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/isSmallHeartSelected.imageset/icon-2@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/navigationBackIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/navigationBackIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/navigationBackIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/navigationBackIcon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/profileIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/profileIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/profileIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/profileIcon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/sendIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/sendIcon.imageset/upload.png
  HOMEAT/Global/Resource/Assets.xcassets/sendIcon.imageset/upload@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/sendIcon.imageset/upload@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/warmgray3.colorset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/warmgray6.colorset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/warmgray8.colorset/Contents.json
  HOMEAT/Presentation/TalkScene/Controller/DeclareViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/RecipeViewController.swift
  HOMEAT/Presentation/TalkScene/View/DeclareView.swift
  HOMEAT/Presentation/TalkScene/View/PostContentView.swift
  HOMEAT/Presentation/TalkScene/View/ReplyReactionView.swift
  HOMEAT/Presentation/TalkScene/View/ReplyTextView.swift
  HOMEAT/Presentation/TalkScene/cell/FoodTalkReplyCell.swift
Labels: :sparkles: Feature, 지우

#71 [HOMEAT-45] Feat[#70] 레시피뷰 구현
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/warmgray10.colorset/Contents.json
  HOMEAT/Presentation/TalkScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/RecipeViewController.swift
  HOMEAT/Presentation/TalkScene/View/IngredientView.swift
  HOMEAT/Presentation/TalkScene/cell/FoodTalkReplyCell.swift
  HOMEAT/Presentation/TalkScene/cell/RecipeStepCell.swift
Labels: :sparkles: Feature, 지우

#74 [HOMEAT-39] Feat [#62] 세부 정보 추가 UI구현
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/gpsIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/gpsIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/gpsIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/gpsIcon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/searchIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/searchIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/searchIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/searchIcon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Base/ProgressViewController.swift
  HOMEAT/Presentation/OnboardingScene/Components/ContinueButton.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SearchDistrictViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetBirthViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetDistrictViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetExpenseViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetIncomeViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetNicknameViewController.swift
Labels: :sparkles: Feature, 상준

#76 Feature/homeat 47
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/DeleteButton.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/DeleteButton.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/DeleteButton.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/DeleteButton.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/TalkWriteButton.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/TalkWriteButton.imageset/icon-12.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/TalkWriteButton.imageset/icon-12@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/TalkWriteButton.imageset/icon-12@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenDelete.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenDelete.imageset/tag-x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenDelete.imageset/tag-x@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenDelete.imageset/tag-x@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenHashTag.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenHashTag.imageset/hash-tag.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenHashTag.imageset/hash-tag@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/greenHashTag.imageset/hash-tag@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/woosuck.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/woosuck.imageset/woosuck.jpeg
  HOMEAT/Global/Resource/Fonts.swift
  HOMEAT/Presentation/TalkScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/InfoTalkTableViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/PhotoCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoPostViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoWriteViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/TagPlusViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Model/Mode.swift
  HOMEAT/Presentation/TalkScene/InfoScene/View/InfoPostContentView.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/FoodTalkCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/FoodTalkReplyCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/RecipeStepCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/DeclareViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/RecipeViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/DeclareView.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/IngredientView.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/PostContentView.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/ReplyReactionView.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/ReplyTextView.swift
  HOMEAT/Presentation/TalkScene/TalkViewController.swift
Labels: 민솔

#78 [HOMEAT-46] Feat[#72] 집밥토크 글작성 및 레시피 작성 기능 구현
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/ImageDeleteButton.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/ImageDeleteButton.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/ImageDeleteButton.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/ImageDeleteButton.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/addIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/addIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/addIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/addIcon.imageset/icon@3x.png
  HOMEAT/Info.plist
  HOMEAT/Presentation/TalkScene/InfoScene.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/RecipeWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/StepWriteController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/FoodTalkCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/FoodTalkReplyCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/PhotoViewCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/RecipeStepCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/RecipeWriteViewCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/IngredientView.swift
  HOMEAT/Presentation/TalkScene/MealScene/ReplyTextView.swift
  HOMEAT/Presentation/TalkScene/TalkViewController.swift
Labels: :sparkles: Feature, 지우

#83 [HOMEAT-54] 성별설정뷰 재추가 및 세부지출확인 제약조건 수정
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Presentation/HomeScene/Controller/PayCheckDetailViewController.swift
  HOMEAT/Presentation/HomeScene/Controller/PayCheckViewController.swift
  HOMEAT/Presentation/HomeScene/View/PayCheckView.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetGenderViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/IngredientView.swift
  HOMEAT/Presentation/TalkScene/MealScene/ReplyTextView.swift
Labels: :hammer: Refactor, 상준
