Repository Homeat/HOMEAT_iOS, pull requests merged in 2024-04, with the labels that each got.

#26 Feat/#25 homeat report
  HOMEAT/Global/Resource/Assets.xcassets/warmgray.colorset/Contents.json
  HOMEAT/Presentation/ReportScene/Controller/AnalysisViewController.swift
  MonthView.swift
  WeakView.swift
Labels: ✨ Feature, 민솔

#33 Feat/#31 report week
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/adult_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/adult_meat.imageset/Property 1=charac8.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/adult_meat.imageset/Property 1=charac8@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/adult_meat.imageset/Property 1=charac8@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/angel_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/angel_meat.imageset/Property 1=charac9.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/angel_meat.imageset/Property 1=charac9@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/angel_meat.imageset/Property 1=charac9@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/baby_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/baby_meat.imageset/icon-3.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/baby_meat.imageset/icon-3@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/baby_meat.imageset/icon-3@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/born_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/born_meat.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/born_meat.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/born_meat.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/egg_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/egg_meat.imageset/Property 1=charac1.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/egg_meat.imageset/Property 1=charac1@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/egg_meat.imageset/Property 1=charac1@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/infant_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/infant_meat.imageset/icon-2.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/infant_meat.imageset/icon-2@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/infant_meat.imageset/icon-2@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/lockReport.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/lockReport.imageset/icon-8.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/lockReport.imageset/icon-8@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/lockReport.imageset/icon-8@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/magic_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/magic_meat.imageset/icon-6.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/magic_meat.imageset/icon-6@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/magic_meat.imageset/icon-6@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/smileIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/smileIcon.imageset/icon-7.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/smileIcon.imageset/icon-7@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/smileIcon.imageset/icon-7@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/student_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/student_meat.imageset/icon-4.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/student_meat.imageset/icon-4@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/student_meat.imageset/icon-4@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/toddler_meat.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/toddler_meat.imageset/Property 1=charac5.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/toddler_meat.imageset/Property 1=charac5@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/WeekReport/toddler_meat.imageset/Property 1=charac5@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/turquoiseDarkGray.colorset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/turquoiseRed.colorset/Contents.json
  HOMEAT/Presentation/ReportScene/Controller/AnalysisViewController.swift
  HOMEAT/Presentation/ReportScene/Controller/Cell/WeekCollectionViewCell.swift
  HOMEAT/Presentation/ReportScene/Controller/WeekLookViewController.swift
  HOMEAT/Presentation/ReportScene/Model/WeekCellModel.swift
  HOMEAT/Presentation/ReportScene/View/MonthView.swift
  HOMEAT/Presentation/ReportScene/View/WeakView.swift
  HOMEAT/Presentation/ReportScene/View/WeekCellView.swift
Labels: 민솔

#32 Feat/#22 food talk UI
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/dropdown.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/dropdown@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/dropdown@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/icon-2.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/icon-2@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/icon-2@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/icon-3.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/icon-3@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/icon-3@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/icon@3x.png
  HOMEAT/Presentation/TalkScene/Cell/FoodTalkCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/TalkViewController.swift
Labels: 지우

#36 Feat/#22 food talk UI 다시 머지
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/dropdown.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/dropdown@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/dropdown.imageset/dropdown@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/icon-2.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/icon-2@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-2.imageset/icon-2@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/icon-3.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/icon-3@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon-3.imageset/icon-3@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/icon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/plusIcon.imageset/Contents 2.json
  HOMEAT/Presentation/TalkScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/Controller/TalkViewController.swift
  HOMEAT/Presentation/TalkScene/cell/FoodTalkCollectionViewCell.swift
Labels: ✨ Feature, 지우

#37 Feat/#29 api setting
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Base/APIEventLogger.swift
  HOMEAT/Network/Base/HTTPHeaderField.swift
  HOMEAT/Network/Base/NetworkResult.swift
  HOMEAT/Network/Base/TargetType.swift
Labels: 📬 API, 석호

#40 Action manual 세팅
  .github/workflows/Jira-Issue-Link.yml
Labels: ⚙ Setting, 상준

#47 Feat/#38 onboarding UI
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Application/AppDelegate.swift
  HOMEAT/Application/SceneDelegate.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/OnBoardingViewController.swift
  HOMEAT/Presentation/OnboardingScene/View/WelcomeView.swift
Labels: :sparkles: Feature, 석호

#49 Feat/#30 pay check UI
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Application/SceneDelegate.swift
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/eatoutIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/eatoutIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/eatoutIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/eatoutIcon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/homefoodIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/homefoodIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/homefoodIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/homefoodIcon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/leftMoneyIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/leftMoneyIcon.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/leftMoneyIcon.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/leftMoneyIcon.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/nextButtonIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/nextButtonIcon.imageset/polygonCalender.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/nextButtonIcon.imageset/polygonCalender@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/nextButtonIcon.imageset/polygonCalender@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/previousButtonIcon.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/previousButtonIcon.imageset/polygonCalender.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/previousButtonIcon.imageset/polygonCalender@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/previousButtonIcon.imageset/polygonCalender@3x.png
  HOMEAT/Presentation/HomeScene/Cell/CalendarCollectionViewCell.swift
  HOMEAT/Presentation/HomeScene/Controller/PayAddViewController.swift
  HOMEAT/Presentation/HomeScene/Controller/PayCheckDetailViewController.swift
  HOMEAT/Presentation/HomeScene/Controller/PayCheckViewController.swift
  HOMEAT/Presentation/HomeScene/View/CalendarView.swift
  HOMEAT/Presentation/HomeScene/View/EatoutCheckView.swift
  HOMEAT/Presentation/HomeScene/View/HomeView.swift
  HOMEAT/Presentation/HomeScene/View/HomefoodCheckView.swift
  HOMEAT/Presentation/HomeScene/View/PayCheckView.swift
Labels: :sparkles: Feature, 상준
