Repository Homeat/HOMEAT_iOS, pull requests merged in 2024-07, with the labels that each got.

#103 Api/homeat 78
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/turquoiseGreen.colorset/Contents.json
  HOMEAT/Network/Analysis/DTO/Request/AnalysisMonthRequestBodyDTO.swift
  HOMEAT/Network/Base/HOMEATRequestInterceptor.swift
  HOMEAT/Network/WeekLook/DTO/Response/ErrorData.swift
  HOMEAT/Network/WeekLook/DTO/Response/WeekLookResponseDTO.swift
  HOMEAT/Network/WeekLook/Service/WeekLookService.swift
  HOMEAT/Presentation/HomeScene/Controller/PayCheckViewController.swift
  HOMEAT/Presentation/HomeScene/View/CalendarView.swift
  HOMEAT/Presentation/ReportScene/Controller/AnalysisViewController.swift
  HOMEAT/Presentation/ReportScene/Controller/WeekLookViewController.swift
  HOMEAT/Presentation/ReportScene/View/MonthView.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/PhotoCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoWriteViewController.swift
Labels: 민솔

#105 Feat[#79] 파일 수정
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Analysis/DTO/Request/AnalysisDetailRequestBodyDTO.swift
  HOMEAT/Network/Analysis/DTO/Response/AnalysisDetailResponseDTO.swift
  HOMEAT/Network/Analysis/Router/AnalysisTarget.swift
  HOMEAT/Network/Analysis/Service/AnalysisService.swift
  HOMEAT/Presentation/ReportScene/Controller/AnalysisViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/PhotoCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoWriteViewController.swift
Labels: 민솔

#109 Api/homeat 84
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Presentation/ReportScene/Controller/AnalysisViewController.swift
  HOMEAT/Presentation/ReportScene/View/CustomPieChartRenderer.swift
  HOMEAT/Presentation/ReportScene/View/MonthView.swift
  HOMEAT/Presentation/ReportScene/View/WeekView.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoWriteViewController.swift
Labels: 민솔

#110 Api/homeat 75
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/FoodTalk/DTO/Request/FoodTalkSaveRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/CheckOneResponseDTO.swift
  HOMEAT/Network/FoodTalk/Router/FoodTalkTarget.swift
  HOMEAT/Network/FoodTalk/Service/FoodTalkService.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/PhotoCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/FoodTalkCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/RecipeStepCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/CommentDeclareViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/CommentDeclareWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/DeclareViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/DeclareWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/RecipeViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/RecipeWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/StepWriteController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/FoodTalkCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/RecipeStepCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/PostContentView.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/ReplyReactionView.swift
Labels: :computer: API, 지우

#115 Api/homeat 68
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Base/KeychainHandler.swift
  HOMEAT/Network/Onboarding/DTO/Request/EmailCertificationRequestBodyDTO.swift
  HOMEAT/Network/Onboarding/DTO/Request/EmailSignUpRequestBodyDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/EmailCertificationResponseDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/EmailSignUpResponseDTO.swift
  HOMEAT/Network/Onboarding/Router/OnboardingTarget.swift
  HOMEAT/Network/Onboarding/Service/OnboardingService.swift
  HOMEAT/Presentation/OnboardingScene/Controller/CompleteSignupViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/FindPasswordViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetBirthViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetExpenseViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetGenderViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetIncomeViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetNicknameViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SignUpViewController.swift
Labels: :computer: API

#119 [Fix] Root 연결안된 tagButton 삭제
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Base/HOMEATRequestInterceptor.swift
Labels: :lady_beetle: BugFix

#121 Api/homeat 88
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/InfoTalk/DTO/Response/PostInfoResponseDTO.swift
  HOMEAT/Network/InfoTalk/Router/InfoTalkTarget.swift
  HOMEAT/Network/InfoTalk/Service/InfoTalkService.swift
  HOMEAT/Presentation/HomeScene/Controller/PayCheckViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/InfoReplyTableViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoCommentDeclareViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoCommentDeclareWriteViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoPostViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/View/InfoPostContentView.swift
  HOMEAT/Presentation/TalkScene/InfoScene/View/InfoReplyTextView.swift
Labels: :computer: API, 민솔

#124 Bug fix/homeat 92
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/FoodTalk/Router/FoodTalkTarget.swift
  HOMEAT/Network/InfoTalk/DTO/Request/ComplainReplyRequestBodyDTO.swift
  HOMEAT/Network/InfoTalk/Router/InfoTalkTarget.swift
  HOMEAT/Network/InfoTalk/Service/InfoTalkService.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoCommentDeclareViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoCommentDeclareWriteViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoPostViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/View/InfoPostContentView.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/RecipeStepCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/CommentDeclareViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/CommentDeclareWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/RecipeWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/StepWriteController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/RecipeStepCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/RecipeWriteViewCell.swift
Labels: :lady_beetle: BugFix, 지우

#128 Feat[#95] 회원가입 및 로그인
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Base/HOMEATRequestInterceptor.swift
  HOMEAT/Network/Base/KeychainHandler.swift
  HOMEAT/Network/Base/TargetType.swift
  HOMEAT/Network/Onboarding/DTO/Request/MyOnboardingRequestBodyDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/AuthCodeResponseDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/EmailJoinResponseDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/TokenRefreshResponseDTO.swift
  HOMEAT/Network/Onboarding/Router/OnboardingTarget.swift
  HOMEAT/Network/Onboarding/Service/OnboardingService.swift
  HOMEAT/Presentation/OnboardingScene/Controller/CompleteSignupViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/OnBoardingViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetBirthViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetExpenseViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetGenderViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetIncomeViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SignUpViewController.swift
Labels: 민솔

#131 Feature/homeat 96
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/logo.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/logo.imageset/logo.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/logo.imageset/logo@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/logo.imageset/logo@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/termUncheck.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/termUncheck.imageset/icon.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/termUncheck.imageset/icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/termUncheck.imageset/icon@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/Logo.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/Logo.imageset/Logo.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/Logo.imageset/Logo@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/HomeView/Logo.imageset/Logo@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/termCheck.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/termCheck.imageset/Icon.png
  HOMEAT/Global/Resource/Assets.xcassets/termCheck.imageset/Icon@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/termCheck.imageset/Icon@3x.png
  HOMEAT/Presentation/OnboardingScene/Controller/FirstPolicyViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/ForthPolicyViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SecondPolicyViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/TermsViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/ThirdPolicyViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/View/InfoPostContentView.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/PostContentView.swift
Labels: :sparkles: Feature, 지우

#132 Api/homeat 97
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Application/SceneDelegate.swift
  HOMEAT/Network/Base/HOMEATRequestInterceptor.swift
  HOMEAT/Network/MyPage/DTO/Request/MyPageEditRequestBodyDTO.swift
  HOMEAT/Network/MyPage/Router/MyPageTarget.swift
  HOMEAT/Network/MyPage/Service/MyPageService.swift
  HOMEAT/Network/Onboarding/DTO/Request/EmailVerificationRequestBodyDTO.swift
  HOMEAT/Network/Onboarding/DTO/Request/FindPasswordRequestBodyDTO.swift
  HOMEAT/Network/Onboarding/DTO/Response/EmailResponseDTO.swift
  HOMEAT/Network/Onboarding/Router/OnboardingTarget.swift
  HOMEAT/Network/Onboarding/Service/OnboardingService.swift
  HOMEAT/Presentation/HomeScene/Controller/HomeViewController.swift
  HOMEAT/Presentation/MyPageScene/Controller/EditIncomeViewController.swift
  HOMEAT/Presentation/MyPageScene/Controller/FinalLeaveViewController.swift
  HOMEAT/Presentation/MyPageScene/Controller/LeaveViewController.swift
  HOMEAT/Presentation/MyPageScene/Controller/MyPageViewController.swift
  HOMEAT/Presentation/MyPageScene/Controller/UserInfoModifyViewController.swift
  HOMEAT/Presentation/MyPageScene/Controller/UserInfoViewController.swift
  HOMEAT/Presentation/MyPageScene/View/PresentIncomeView.swift
  HOMEAT/Presentation/OnboardingScene/Controller/CompleteSignupViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/FindPasswordViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/FinishPasswordViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/OnBoardingViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/Onboarding/SetBirthViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/Onboarding/SetDistrictViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/Onboarding/SetExpenseViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/Onboarding/SetGenderViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/Onboarding/SetIncomeViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/Onboarding/SetNicknameViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SignUpViewController.swift
Labels: 민솔

#135 Bug fix/homeat 100
  HOMEAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HOMEAT/Network/Base/HOMEATRequestInterceptor.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetExpenseViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetIncomeViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/InfoReplyTableViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/View/InfoPostContentView.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/FoodTalkReplyCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/RecipeWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/StepWriteController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/FoodTalkReplyCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/View/PostContentView.swift
Labels: :lady_beetle: BugFix, 지우
