Repository Homeat/HOMEAT_iOS, pull requests merged in 2024-06, with the labels that each got.

#84 Feature/homeat 42
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Presentation/OnboardingScene/Controller/ChangePasswordViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/EmailApproveViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/LoginViewController.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SignUpViewController.swift
Labels: :sparkles: Feature, 석호

#86 Api/homeat 53
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Base/HTTPHeaderField.swift
  HOMEAT/Network/Base/NetworkService.swift
  HOMEAT/Network/Base/TargetType.swift
  HOMEAT/Network/FoodTalk/DTO/Request/CheckOneRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/CommentReportRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/CommentWriteRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/DeleteCommentRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/DeleteLoveRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/DeletePostRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/DeleteReplyRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/FoodTalkSaveRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/LatestOrderRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/LoveOrderRequestBody.swift
  HOMEAT/Network/FoodTalk/DTO/Request/LoveRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/OldestOrderRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/PostReportRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/RecipeSaveRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/ReplyReportRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/ReplyWriteRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Request/ViewOrderRequestBodyDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/CheckOneResponseDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/FoodTalkLatestResponseDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/FoodTalkLoveDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/LatestOrderResponseDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/LoveOrderResponseDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/OldestOrderResponseDTO.swift
  HOMEAT/Network/FoodTalk/DTO/Response/ViewOrderResponseDTO.swift
  HOMEAT/Network/FoodTalk/Router/FoodTalkTarget.swift
  HOMEAT/Network/FoodTalk/Service/FoodTalkService.swift
  HOMEAT/Presentation/OnboardingScene/Controller/SetBirthViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/Cell/FoodTalkReplyCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/CommentDeclareViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/CommentDeclareWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/DeclareViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/DeclareWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodPostViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/FoodTalkViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/RecipeWriteViewController.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/FoodTalkReplyCell.swift
  HOMEAT/Presentation/TalkScene/MealScene/Controller/cell/RecipeWriteViewCell.swift
Labels: :computer: API, 지우

#90 [Feat] TagButton 커스텀 추가
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Presentation/MyPageScene/Components/TagButton.swift
  HOMEAT/Presentation/OnboardingScene/Controller/EmailApproveViewController.swift
Labels: :sparkles: Feature, :lady_beetle: BugFix, 석호

#93 Feature/homeat 66
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/tagPlusButton.imageset/Contents.json
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/tagPlusButton.imageset/Group 4857.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/tagPlusButton.imageset/Group 4857@2x.png
  HOMEAT/Global/Resource/Assets.xcassets/FoodTalkView/tagPlusButton.imageset/Group 4857@3x.png
  HOMEAT/Global/Resource/Assets.xcassets/turquoiseGray2.colorset/Contents.json
  HOMEAT/Network/Analysis/DTO/Request/AnalysisWeekRequestBodyDTO.swift
  HOMEAT/Network/Analysis/DTO/Response/AnalysisMonthResponseDTO.swift
  HOMEAT/Network/Analysis/DTO/Response/AnalysisWeekResponseDTO.swift
  HOMEAT/Network/Analysis/Router/AnalysisTarget.swift
  HOMEAT/Network/Base/NetworkService.swift
  HOMEAT/Network/InfoTalk/DTO/Request/InfoTalkSaveRequestBodyDTO.swift
  HOMEAT/Network/InfoTalk/Router/InfoTalkTarget.swift
  HOMEAT/Network/InfoTalk/Service/InfoTalkService.swift
  HOMEAT/Network/WeekLook/DTO/Response/ReportBadge.swift
  HOMEAT/Network/WeekLook/DTO/Response/WeekLookResponseDTO.swift
  HOMEAT/Network/WeekLook/Router/WeekLookTarget.swift
  HOMEAT/Network/WeekLook/Service/WeekLookService.swift
  HOMEAT/Presentation/ReportScene/Controller/AnalysisViewController.swift
  HOMEAT/Presentation/ReportScene/Controller/Cell/WeekCollectionViewCell.swift
  HOMEAT/Presentation/ReportScene/Controller/WeekLookViewController.swift
  HOMEAT/Presentation/ReportScene/View/MonthView.swift
  HOMEAT/Presentation/ReportScene/View/WeekCellView.swift
  HOMEAT/Presentation/ReportScene/View/WeekView.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/PhotoCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/TagCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/Cell/TagPlusCollectionViewCell.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoTalkViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/InfoWriteViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Controller/TagPlusViewController.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Model/Mode.swift
  HOMEAT/Presentation/TalkScene/InfoScene/Model/TagItem.swift
Labels: 민솔

#97 Api/homeat 71
  HOMEAT.xcodeproj/project.pbxproj
  HOMEAT/Network/Home/DTO/Request/CalendarCheckRequestBodyDTO.swift
  HOMEAT/Network/Home/DTO/Request/CalendarDailyRequestBodyDTO.swift
  HOMEAT/Network/Home/DTO/Response/CalendarCheckResponseDTO.swift
  HOMEAT/Network/Home/DTO/Response/CalendarDailyResponseDTO.swift
  HOMEAT/Network/Home/Router/HomeSceneTarget.swift
  HOMEAT/Network/Home/Service/HomeSceneService.swift
  HOMEAT/Presentation/HomeScene/Cell/CalendarCollectionViewCell.swift
  HOMEAT/Presentation/HomeScene/Controller/PayCheckDetailViewController.swift
  HOMEAT/Presentation/HomeScene/Controller/PayCheckViewController.swift
  HOMEAT/Presentation/HomeScene/View/CalendarView.swift
  HOMEAT/Presentation/HomeScene/View/PayCheckView.swift
Labels: 민솔
